version: '3.1'

services:
  appgo:
    image: golang:1.19
    volumes:
      - /appgo:/go/src/app
    ports:
      - "8000:8000"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newtec
      mysql_password: root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql